# Generated by Django 3.2.18 on 2023-07-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('buy', models.CharField(max_length=50)),
            ],
        ),
    ]
