# Generated by Django 4.2.3 on 2023-07-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="reason",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
