# Generated by Django 4.2.3 on 2023-07-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_tracker_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="accounts",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(default=0)),
            ],
        ),
    ]
