# Generated by Django 4.2.3 on 2023-07-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
