# Generated by Django 4.2.3 on 2023-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_alter_accounts_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="buy",
            field=models.IntegerField(max_length=50),
        ),
    ]
